name: flutter_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bot_toast: ^4.0.2

dev_dependencies:
  build_runner: ^2.1.10
  hive_generator: ^1.1.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
