// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_task/test/controllers/grocery_controller/grocery_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i11;

import 'package:flutter_task/app/core/models/cart/cart_model.dart' as _i9;
import 'package:flutter_task/app/core/models/category_model.dart' as _i6;
import 'package:flutter_task/app/core/models/deals_model.dart' as _i7;
import 'package:flutter_task/app/core/models/favorite/favorite_model.dart'
    as _i8;
import 'package:flutter_task/app/core/models/location_information.dart' as _i5;
import 'package:flutter_task/app/modules/home/grocery/grocery_controller.dart'
    as _i4;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i10;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroceryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceryController extends _i1.Mock implements _i4.GroceryController {
  MockGroceryController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.LocationInformation> get locationInformation => (super.noSuchMethod(
        Invocation.getter(#locationInformation),
        returnValue: <_i5.LocationInformation>[],
      ) as List<_i5.LocationInformation>);
  @override
  set locationInformation(
          List<_i5.LocationInformation>? _locationInformation) =>
      super.noSuchMethod(
        Invocation.setter(
          #locationInformation,
          _locationInformation,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i6.CategoryModel> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i6.CategoryModel>[],
      ) as List<_i6.CategoryModel>);
  @override
  set categories(List<_i6.CategoryModel>? _categories) => super.noSuchMethod(
        Invocation.setter(
          #categories,
          _categories,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i7.DealsModel> get deals => (super.noSuchMethod(
        Invocation.getter(#deals),
        returnValue: <_i7.DealsModel>[],
      ) as List<_i7.DealsModel>);
  @override
  set deals(List<_i7.DealsModel>? _deals) => super.noSuchMethod(
        Invocation.setter(
          #deals,
          _deals,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Box<_i8.FavoriteModel> get favoriteBox => (super.noSuchMethod(
        Invocation.getter(#favoriteBox),
        returnValue: _FakeBox_0<_i8.FavoriteModel>(
          this,
          Invocation.getter(#favoriteBox),
        ),
      ) as _i2.Box<_i8.FavoriteModel>);
  @override
  set favoriteBox(_i2.Box<_i8.FavoriteModel>? _favoriteBox) =>
      super.noSuchMethod(
        Invocation.setter(
          #favoriteBox,
          _favoriteBox,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Box<_i9.CartModel> get cartBox => (super.noSuchMethod(
        Invocation.getter(#cartBox),
        returnValue: _FakeBox_0<_i9.CartModel>(
          this,
          Invocation.getter(#cartBox),
        ),
      ) as _i2.Box<_i9.CartModel>);
  @override
  set cartBox(_i2.Box<_i9.CartModel>? _cartBox) => super.noSuchMethod(
        Invocation.setter(
          #cartBox,
          _cartBox,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);
  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);
  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);
  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addOrRemoveToFavorites(
    _i7.DealsModel? dealsModel,
    bool? isFavorite,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addOrRemoveToFavorites,
          [
            dealsModel,
            isFavorite,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addOrRemoveToCart(
    _i7.DealsModel? dealsModel,
    bool? isFoundCart,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addOrRemoveToCart,
          [
            dealsModel,
            isFoundCart,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Disposer addListener(_i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i10.Disposer);
  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListenerId(
    Object? id,
    _i11.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Disposer addListenerId(
    Object? key,
    _i10.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i10.Disposer);
  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
